#!/usr/bin/env python3
"""
kf-langextract: Run structured extraction using google/langextract.
Usage: python run-extraction.py --text "..." --prompt "..." [options]

Generated by kf-langextract skill. Modify inline as needed.
"""
import argparse
import json
import os
import sys

try:
    import langextract as lx
except ImportError:
    print("ERROR: langextract not installed. Run: pip install langextract")
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Run langextract extraction")
    parser.add_argument("--text", help="Source text (inline)")
    parser.add_argument("--file", help="Source text file path")
    parser.add_argument("--url", help="Source URL")
    parser.add_argument("--prompt", required=True, help="Extraction prompt description")
    parser.add_argument("--model", default="gemini-2.5-flash", help="Model ID")
    parser.add_argument("--passes", type=int, default=2, help="Extraction passes")
    parser.add_argument("--output", default="extraction_output", help="Output name")
    parser.add_argument("--viz", action="store_true", help="Generate HTML visualization")
    args = parser.parse_args()

    # Determine source
    if args.url:
        source = args.url
    elif args.file:
        with open(args.file, "r") as f:
            source = f.read()
    elif args.text:
        source = args.text
    else:
        source = sys.stdin.read()

    if not source.strip():
        print("ERROR: No source text provided")
        sys.exit(1)

    # Build examples from stdin JSON if piped
    examples = []
    # NOTE: Define your examples inline below or pipe JSON array via stdin

    print(f"Extracting from {len(source)} chars using {args.model}...")
    print(f"Prompt: {args.prompt}")

    result = lx.extract(
        text_or_documents=source,
        prompt_description=args.prompt,
        examples=examples,
        model_id=args.model,
        extraction_passes=args.passes,
    )

    # Save
    lx.io.save_annotated_documents([result], output_name=args.output, output_dir=".")

    # Report
    total = len(result.extractions)
    grounded = sum(1 for e in result.extractions if e.char_interval is not None)
    ungrounded = total - grounded

    print(f"\n=== Results ===")
    print(f"Total: {total} | Grounded: {grounded} | Ungrounded: {ungrounded}")
    for e in result.extractions:
        loc = f"chars {e.char_interval}" if e.char_interval else "UNGROUNDED"
        attrs = f" | attrs: {e.attributes}" if e.attributes else ""
        print(f"  [{e.extraction_class}] \"{e.extraction_text}\" @ {loc}{attrs}")

    print(f"\nSaved to {args.output}.jsonl")

    if args.viz:
        html = lx.visualize(f"{args.output}.jsonl")
        content = html.data if hasattr(html, "data") else html
        with open(f"{args.output}.html", "w") as f:
            f.write(content)
        print(f"Visualization: {args.output}.html")


if __name__ == "__main__":
    main()
